### ISSUE TITLE
Use environment flag as condition in terraform code to remove private instance from XC3 project for Development purpose

### ISSUE THREAD

**Issue by yaseenzafar123** [XgridInc/xc3#43]
**User stories**

As an XCBG Cloud Engineer, I want to add a condition to remove a private instance from the XC3 project in Terraform and use public instance for Development purpose

**Acceptance Criteria**

- [x] The condition for removing a private instance should be configurable through variables or input parameters in the Terraform code.
- [x] Add condition in a way such that for dev environment, Load balancer and private subnet is removed for dev flag
- [x] The Terraform code should handle the removal of the private instance gracefully, ensuring any dependencies or associated resources are properly managed.
- [x] Test the code to verify if it working properly or not.
- [x] The code changes should be properly reviewed and approved by a peer or team lead.

**Comment by waji46** [comment]
Utilizing an environment variable, the application prompts for the desired environment. If the environment is set to "Prod," the infrastructure will be deployed in the standard manner. However, if the user sets the environment to "dev," the Xc3 infrastructure will be deployed with minimal resources, eliminating any unnecessary elements that are not essential for the development process.

**Comment by yaseenzafar123** [comment]
Wajahat is currently deploying new infra while changing the CIDR. Lambdas are in public subnet Expected result: The lambdas should be able to communicate internally and link list lambda should be able to retrieve the data from SSM.
Unexpected result: The lambda won't be able to get SSM parameters. Then we will have to look for other approaches. Like we might have to use NAT gateway with private subnet configured for lambdas or other approaches can be taken as well.

**Comment by waji46** [comment]
Worked on the lambda call to Cost explorer issue, found out that lambda can not communicate with the internet, it only has Private IP in public subnet, so it cannot communicate with the internet without the nat gateway.

Link : [Public Lambda Subnet issue](https://stackoverflow.com/questions/52992085/why-cant-an-aws-lambda-function-inside-a-public-subnet-in-a-vpc-connect-to-the)



Suggestion was to update the infrastructure and made the lambda public.
By making lambda public the API calls to the Cost Explorer was costing too much.

**Comment by waji46** [comment]
Having issue with the lambda's in the Public subnet, lambda's cannot be assigned a public IP address, if it needs to connect to internet, which will require a NAT Gateway, so changed our approach to make our Ec2 in public subnet, lambdas in private subnet and no load balancer.
